package pkg

var TANJUNG_PRIOK = []string{
	"Ancol",
	"Cilincing",
	"Kalibaru",
	"Kamal Muara",
	"Kapuk Muara",
	"Kebon Bawang",
	"Kelapa Gading Barat",
	"Kelapa Gading Timur",
	"Koja",
	"Lagoa",
	"Marunda",
	"Pademangan Barat",
	"Pademangan Timur",
	"Papanggo",
	"Pegangsaan Dua",
	"Pejagalan",
	"Penjaringan",
	"Pluit",
	"Rawa Badak Selatan",
	"Rawa Badak Utara",
	"Rorotan",
	"Semper Barat",
	"Semper Timur",
	"Sukapura",
	"Sungai Bambu",
	"Sunter Agung",
	"Sunter Jaya",
	"Tanjung Priok",
	"Tugu Selatan",
	"Tugu Utara",
	"Warakas",
}

var KEMAYORAN = []string{
	"Cempaka Putih Barat",
	"Cempaka Putih Timur",
	"Rawasari",
	"Cideng",
	"Duri Pulo",
	"Gambir",
	"Kebon Kelapa",
	"Petojo Selatan",
	"Petojo Utara",
	"Galur",
	"Johar Baru",
	"Kampung Rawa",
	"Tanah Tinggi",
	"Cempaka Baru",
	"Gunung Sahari Selatan",
	"Harapan Mulya",
	"Kebon Kosong",
	"Kemayoran",
	"Serdang",
	"Sumur Batu",
	"Utan Panjang",
	"Cikini",
	"Gondangdia",
	"Kebon Sirih",
	"Menteng",
	"Pegangsaan",
	"Gunung Sahari Utara",
	"Karang Anyar",
	"Kartini",
	"Mangga Dua Selatan",
	"Pasar Baru",
	"Bungur",
	"Kenari",
	"Kramat",
	"Kwitang",
	"Paseban",
	"Senen",
	"Bendungan Hilir",
	"Gelora",
	"Kampung Bali",
	"Karet Tengsin",
	"Kebon Kacang",
	"Kebon Melati",
	"Petamburan",
	"Cengkareng Barat",
	"Cengkareng Timur",
	"Duri Kosambi",
	"Kapuk",
	"Kedaung Kali Angke",
	"Rawa Buaya",
	"Grogol",
	"Jelambar",
	"Jelambar Baru",
	"Tanjung Duren Selatan",
	"Tanjung Duren Utara",
	"Tomang",
	"Wijaya Kusuma",
	"Kalideres",
	"Kamal",
	"Pegadungan",
	"Semanan",
	"Tegal Alur",
	"Duri Kepa",
	"Kebon Jeruk",
	"Kedoya Selatan",
	"Kedoya Utara",
	"Kelapa Dua",
	"Sukabumi Selatan",
	"Sukabumi Utara",
	"Joglo",
	"Kembangan Selatan",
	"Kembangan Utara",
	"Meruya Selatan",
	"Meruya Utara",
	"Srengseng",
	"Jatipulo",
	"Kemanggisan",
	"Kota Bambu Selatan",
	"Kota Bambu Utara",
	"Palmerah",
	"Slipi",
	"Glodok",
	"Keagungan",
	"Krukut",
	"Mangga Besar",
	"Maphar",
	"Pinangsia",
	"Taman Sari",
	"Tangki",
	"Angke",
	"Duri Selatan",
	"Duri Utara",
	"Jembatan Besi",
	"Jembatan Lima",
	"Kali Anyar",
	"Krendang",
	"Pekojan",
	"Roa Malaka",
	"Tambora",
	"Tanah Sereal",
}

var HALIM = []string{
	"Balekambang",
	"Bali Mester",
	"Bambu Apus",
	"Baru",
	"Batu Ampar",
	"Bidara Cina",
	"Cakung Barat",
	"Cakung Timur",
	"Cawang",
	"Ceger",
	"Cibubur",
	"Cijantung",
	"Cilangkap",
	"Cililitan",
	"Cipayung",
	"Cipinang",
	"Cipinang Besar Selatan",
	"Cipinang Besar Utara",
	"Cipinang Cempedak",
	"Cipinang Melayu",
	"Cipinang Muara",
	"Ciracas",
	"Dukuh",
	"Duren Sawit",
	"Gedong",
	"Halim Perdana Kusuma",
	"Jati",
	"Jatinegara",
	"Jatinegara Kaum",
	"Kalisari",
	"Kampung Melayu",
	"Kayu Manis",
	"Kayu Putih",
	"Kebon Manggis",
	"Kebon Pala",
	"Kelapa Dua Wetan",
	"Klender",
	"Kramat Jati",
	"Lubang Buaya",
	"Makasar",
	"Malaka Jaya",
	"Malaka Sari",
	"Munjul",
	"Pal Meriam",
	"Pekayon",
	"Penggilingan",
	"Pinang Ranti",
	"Pisangan Baru",
	"Pisangan Timur",
	"Pondok Bambu",
	"Pondok Kelapa",
	"Pondok Kopi",
	"Pondok Ranggon",
	"Pulo Gadung",
	"Pulo Gebang",
	"Rambutan",
	"Rawa Bunga",
	"Rawa Terate",
	"Rawamangun",
	"Setu",
	"Susukan",
	"Tengah",
	"Ujung Menteng",
	"Utan Kayu Selatan",
	"Utan Kayu Utara",
	"Bangka",
	"Bintaro",
	"Bukit Duri",
	"Ciganjur",
	"Cikoko",
	"Cilandak Barat",
	"Cilandak Timur",
	"Cipedak",
	"Cipete Selatan",
	"Cipete Utara",
	"Cipulir",
	"Duren Tiga",
	"Gandaria Selatan",
	"Gandaria Utara",
	"Grogol Selatan",
	"Grogol Utara",
	"Guntur",
	"Gunung",
	"Jagakarsa",
	"Jati Padang",
	"Kalibata",
	"Karet",
	"Karet Kuningan",
	"Karet Semanggi",
	"Kebagusan",
	"Kebayoran Lama Selatan",
	"Kebayoran Lama Utara",
	"Kebon Baru",
	"Kramat Pela",
	"Kuningan Barat",
	"Kuningan Timur",
	"Lebak Bulus",
	"Lenteng Agung",
	"Mampang Prapatan",
	"Manggarai",
	"Manggarai Selatan",
	"Melawai",
	"Menteng Atas",
	"Menteng Dalam",
	"Pancoran",
	"Pasar Manggis",
	"Pasar Minggu",
	"Pejaten Barat",
	"Pejaten Timur",
	"Pela Mampang",
	"Pengadegan",
	"Pesanggrahan",
	"Petogogan",
	"Petukangan Selatan",
	"Petukangan Utara",
	"Pondok Labu",
	"Pondok Pinang",
	"Pulo",
	"Ragunan",
	"Rawa Barat",
	"Rawajati",
	"Selong",
	"Senayan",
	"Setiabudi",
	"Srengseng Sawah",
	"Tanjung Barat",
	"Tebet Barat",
	"Tebet Timur",
	"Tegal Parang",
	"Ulujami",
}
